export MAIL_SERVER=smtp.googlemail.com
export MAIL_PORT=587
export MAIL_USE_TLS=1
export MAIL_USERNAME=jlimahaverford
export MAIL_PASSWORD=gcastle1!anthony
export MAIL_ADDRESS=jlimahaverford@gmail.com

export TWITTER_CONSUMER_KEY=IcCNshWPGUYnHhxU7WUNpXA9y
export TWITTER_CONSUMER_SECRET=gU621gWnniXN8nU0RE7c5DPru89FnZ1H9q8piprBmMbXOWFP5R
export TWITTER_ACCESS_TOKEN_KEY=4047551081-Zs1Sfz5QIN5N201XW5uHYkCK4FoN7b972DcX7Di
export TWITTER_ACCESS_TOKEN_SECRET=7zYixzVbwZVOQvpJBNEhJJkTHzLmrTX2w4MnIYfclcJUT

export DATABASE_URL="postgresql://localhost/amp"

export FLASK_APP=amp.py

source venv/bin/activate
