"""initial migrate

Revision ID: 03de6affce95
Revises: 
Create Date: 2019-01-29 16:49:15.302308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03de6affce95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitter_username', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_user_twitter_username'), 'twitter_user', ['twitter_username'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('active_amp_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitter_user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=280), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['twitter_user_id'], ['twitter_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweet_timestamp'), 'tweet', ['timestamp'], unique=False)
    op.create_table('twitter_user_follow',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('twitter_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['twitter_user_id'], ['twitter_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('amp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tweet_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amp_timestamp'), 'amp', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_amp_timestamp'), table_name='amp')
    op.drop_table('amp')
    op.drop_table('twitter_user_follow')
    op.drop_index(op.f('ix_tweet_timestamp'), table_name='tweet')
    op.drop_table('tweet')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_twitter_user_twitter_username'), table_name='twitter_user')
    op.drop_table('twitter_user')
    # ### end Alembic commands ###
