"""amps table

Revision ID: 362db3b79580
Revises: 920e39e5ed99
Create Date: 2019-01-20 19:36:21.375523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362db3b79580'
down_revision = '920e39e5ed99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitter_username', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_user_twitter_username'), 'twitter_user', ['twitter_username'], unique=True)
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitter_user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=280), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['twitter_user_id'], ['twitter_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweet_timestamp'), 'tweet', ['timestamp'], unique=False)
    op.create_table('amp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tweet_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amp_timestamp'), 'amp', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_amp_timestamp'), table_name='amp')
    op.drop_table('amp')
    op.drop_index(op.f('ix_tweet_timestamp'), table_name='tweet')
    op.drop_table('tweet')
    op.drop_index(op.f('ix_twitter_user_twitter_username'), table_name='twitter_user')
    op.drop_table('twitter_user')
    # ### end Alembic commands ###
