"""twitter_user_follow

Revision ID: d8ba9da22d12
Revises: 32f78c2a3d65
Create Date: 2019-01-23 16:12:39.343317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ba9da22d12'
down_revision = '32f78c2a3d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_user_follow',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('twitter_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['twitter_user_id'], ['twitter_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_user_follow')
    # ### end Alembic commands ###
